// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portal;

namespace Portal.Migrations
{
    [DbContext(typeof(MailOrderContext))]
    [Migration("20210531033617_MailOrderProject")]
    partial class MailOrderProject
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Portal.Models.RefillOrder", b =>
                {
                    b.Property<int>("RefillOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DrugID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Member_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("NextRefillDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Policy_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("RefillDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RefillOrderLinePolicy_ID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Subscription_ID")
                        .HasColumnType("int");

                    b.HasKey("RefillOrderId");

                    b.HasIndex("RefillOrderLinePolicy_ID");

                    b.ToTable("refillOrders");
                });

            modelBuilder.Entity("Portal.Models.RefillOrderLineItem", b =>
                {
                    b.Property<int>("Policy_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Member_ID")
                        .HasColumnType("int");

                    b.Property<int>("Subscription_ID")
                        .HasColumnType("int");

                    b.HasKey("Policy_ID");

                    b.ToTable("RefillOrderLineItem");
                });

            modelBuilder.Entity("Portal.Models.RefillOrder", b =>
                {
                    b.HasOne("Portal.Models.RefillOrderLineItem", "RefillOrderLine")
                        .WithMany()
                        .HasForeignKey("RefillOrderLinePolicy_ID");

                    b.Navigation("RefillOrderLine");
                });
#pragma warning restore 612, 618
        }
    }
}
